4.
$$
A =
\begin{pmatrix}
    1 & -2 & 8 \\
    7 & 5 & -2 \\
    -2 & 3 & 0 
\end{pmatrix}
, B =
\begin{pmatrix}
    0 & 2 & 4 \\
    1 & -3 & -2 \\
    -2 & 1 & 3
\end{pmatrix}
, C = 
\begin{pmatrix}
    0 & 3 \\
    5 & -4 \\
    7 & -1 
\end{pmatrix}
$$

In [1]:
import numpy as np

A = np.array([[1, -2, 8], [7, 5, -2], [-2, 3, 0]])
B = np.array([[0, 2, 4], [1, -3, -2], [-2, 1, 3]])
C = np.array([[0, 3], [5, -4], [7, -1]])

In [8]:
# 4.1
A + B

array([[ 1,  0, 12],
       [ 8,  2, -4],
       [-4,  4,  3]])

In [7]:
# 4.2
B - A

array([[-1,  4, -4],
       [-6, -8,  0],
       [ 0, -2,  3]])

In [9]:
# 4.3
A @ C

array([[ 46,   3],
       [ 11,   3],
       [ 15, -18]])

In [10]:
# 4.4
A @ B @ C

array([[ 304, -150],
       [  69,   27],
       [-163,   75]])

5.
$$
A =
\begin{pmatrix}
    9 & 2 & 4 \\
    7 & 5 & -5 \\
    6 & -2 & 3 
\end{pmatrix}
, B =
\begin{pmatrix}
    8 & 2 & 4 \\
    0 & 1 & -3 \\
    -2 & 1 & 6
\end{pmatrix}
, C = 
\begin{pmatrix}
    -2 & 0 \\
    4 & 8 \\
    1 & -1 
\end{pmatrix}
$$

In [11]:
A = np.array([[9, 2, 4], [7, 5, -5], [6, -2, 3]])
B = np.array([[8, 2, 4], [0, 1, -3], [-2, 1, 6]])
C = np.array([[-2, 0], [4, 8], [1, -1]])

In [12]:
# 5.1
A + B

array([[17,  4,  8],
       [ 7,  6, -8],
       [ 4, -1,  9]])

In [13]:
# 5.2
B - A

array([[-1,  0,  0],
       [-7, -4,  2],
       [-8,  3,  3]])

In [14]:
# 5.3
A @ C

array([[ -6,  12],
       [  1,  45],
       [-17, -19]])

In [15]:
5.4
A @ B @ C

array([[ 22, 138],
       [-93, 129],
       [ 16,  56]])